### ISSUE TITLE
Slow Permission Checks

### ISSUE THREAD

**Issue by drtshock** [drtshock/Essentials#19]
A lot of people get the notice for slow permission checks. Essentials appears to try to do a lot with permissions. Why not just default back to the Player#hasPermission

**Comment by drtshock** [comment]
Some work toward it here https://github.com/drtshock/Essentials/commit/ac0858dcdbf4dd12e1c1b27d4de822646e625a1b

**Comment by raum266** [comment]
Unsure if related, but the current Snapshot has broken global perms - Specifically, players having "essentials.worlds.*" is not read as * anymore. Only updated the main Essentials package to this one - Still using the same GroupManager.

**Comment by drtshock** [comment]
@raum266 can you paste your startup log in a gist or pastebin for me please? I want to see what it registered. Otherwise, I have a feeling I know what it could be.

**Comment by raum266** [comment]
http://pastebin.com/D4S9EMjK

Removed the address for anti-advertisement, and the WG & Multiverse world loading spam (we have lots of worlds :P)  If you need them for some reason, let me know and I'll do another.

**Comment by drtshock** [comment]
Should be fixed with the vault handler.
