### ISSUE TITLE
EssentialsX Addition to homes.

### ISSUE THREAD

**Issue by zRiaz** [drtshock/Essentials#20]
The permissions for homes should become stackable.
Example:

Riaz has the permission essentials.sethome.multiple.donator (5 homes)
And buys an extra home at the donation store (forexample) and received the permission essentials.sethome.multiple.extra (1 home) Which would make the homes stack so Riaz would be able to set 6 homes. Then when he upgrades his rank to VIP, he received essentials.sethome.multiple.vip (8 homes) but since he has the extra node, he gets 9 homes.

(Just an example), but its definetly something I would find very useful if this could be done.

**Comment by drtshock** [comment]
I wrote a plugin that does something like this. You can just use essentials.sethome.# then it grabs what you have and adds it. I think something like this would be better suited as an addon.

https://mcexchange.org/resources/homelimit.12/ free \o/

**Comment by zRiaz** [comment]
Thanks for the plugin, however I do feel like it wouldnt hurt to get this directly implemented into Essentials so I dont need to use an additional plugin for it. Its not really a major thing to make the permissions stack though :/

If it could be added to Essentials that would be really great. If not then I guess ill just use the plugin.

**Comment by drtshock** [comment]
I don't see how using another plugin is an issue at all. The reason for not stacking the permissions like you said is that it would make home operations take longer than they already do. I'd rather not slow Essentials down at all ;)
