### ISSUE TITLE
Feature Request: Sudo All

### ISSUE THREAD

**Issue by TWSSYesterday** [drtshock/Essentials#23]
Requesting Feature:
- /sudo ** <command>

**Comment by drtshock** [comment]
oh gosh

**Comment by TWSSYesterday** [comment]
xD

**Comment by EvilOlaf** [comment]
I don't think that this would be a very "essential" feature...

**Comment by TWSSYesterday** [comment]
@EvilOlaf It would allow for mass operating of commands, one would argue that that's needed in some form; and it's an essential feature.

**Comment by drtshock** [comment]
It would be quite hilarious and obviously only for ops.

**Comment by TWSSYesterday** [comment]
<3

**Comment by EvilOlaf** [comment]
@TWSSYesterday Didn't think about mass usage, good point.
