### ISSUE TITLE
Essentials issue.

### ISSUE THREAD

**Issue by TWSSYesterday** [drtshock/Essentials#25]
Socialspy makes whole username appear white with no prefix when they're talking if the prefix is long.
![](http://i.imgur.com/NcLoNY6.png)

**Comment by TWSSYesterday** [comment]
Adding onto this, when using /list I get this:

![](http://i.imgur.com/vjktOYq.png)

**Comment by drtshock** [comment]
As far as I know, these are both done as intended. What is the issue here?

**Comment by TWSSYesterday** [comment]
Prefixes aren't appearing, same occurs in tab too.

**Comment by EvilOlaf** [comment]
Afaik there are other plugins that can modify the tab list. Also as long as I know socialspy never displayed colors or pre-/suffixes?
Just

**Comment by drtshock** [comment]
Ess doesn't use scoreboards to set prefixes, which is what would be in the tab. Socialspy has never displayed prefixes as it doesn't matter. You are just spying on their private messages.

**Comment by TWSSYesterday** [comment]
The same happens in tab though, is this not an issue?

**Comment by EvilOlaf** [comment]
Nope. It's the default behavior.

**Comment by drtshock** [comment]
Like I said, we don't deal with tab at all.

**Comment by TWSSYesterday** [comment]
Hmm, might be PermissionsEx
