### ISSUE TITLE
Question: Difference between Spigots Essentials and this one?

### ISSUE THREAD

**Issue by EvilOlaf** [drtshock/Essentials#26]
As written this is more a question rather than an issue ;)

Spigot maintains (well from time to time ^^) their own version of Essentials which can be found here: https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/

My question is what is the actual intention of this fork?

Best regards
Olaf

**Comment by drtshock** [comment]
Spigot doesn't maintain it. They just made a commit to make it compile on 1.8. I'm actually maintaining my fork with a few new features and mainly fixes.

**Comment by EvilOlaf** [comment]
Aight, sound nice.
Thanks.
