### ISSUE TITLE
Better SocialSpy

### ISSUE THREAD

**Issue by ISanderI** [drtshock/Essentials#27]
Basically this:
https://www.mc-market.org/threads/12292/

It shows examples of what could be added. More specificly to spying on the /r command by letting you know who he is replying to instead of just plain /r (msg) it shows something like player1 replies to player2 (msg) or something like that.

Not too important, but I think it could be a nice feature.

**Comment by drtshock** [comment]
Can you make these into separate tickets please. I do like the social spy idea though :)

**Comment by zRiaz** [comment]
Fine.

**Comment by drtshock** [comment]
I went to redo how it does it already a bit but the issue with that is it led to breaking any socialspy command that isn't a message (jail, etc). This is going to be a bit more involved than I anticipated.

**Comment by ISanderI** [comment]
Soo is this not going to be implemented at all or just a bit hard to add atm?

**Comment by SupaHam** [comment]
This has been introduced in 75d1254. You can grab the feature from [build 405](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
