### ISSUE TITLE
Error with newbie spawn teleportation

### ISSUE THREAD

**Issue by zRiaz** [drtshock/Essentials#32]
http://pastebin.com/HD1N6JvY
Got this error when logging in for the first time (after removing my /world folder)

Doubt its anything serious, but yea its atleast an error, so thought I would report it.
(I think my spawn was inside the ground etc, which caused this.)

**Comment by drtshock** [comment]
That's just a notification, not sure why there is a stack trace.

**Comment by zRiaz** [comment]
Yea, I reported it due to the stack trace as I wasnt sure why that would show up.

**Comment by vemacs** [comment]
Doesn't seem to be an actual issue, this is mainline Essentials behavior as well. Kind of an edge case.
