### ISSUE TITLE
Timings

### ISSUE THREAD

**Issue by JustOneMoreBlock** [drtshock/Essentials#33]
This was noticeable in the original Essentials and figure I'll report this here and see if it's something you can look into.

http://timings.aikar.co/?url=11119934

http://i.imgur.com/L4175ce.png

**Comment by Kakifrucht** [comment]
Those timings are pretty terrible, Essentials does not have much to do with your bad performance.

**Comment by drtshock** [comment]
That's pretty high for how few players you have..

Kaki: the timings are fine. It just looks like he has a slow CPU or something.

@JustOneMoreBlock what are the specs of the machine you're on? And did you have any times where you were like "botted" where you'd have hundreds of people joining in the span of a second or two.
