### ISSUE TITLE
modifying chat event is null

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Essentials#34]
trying this version of essentials out.. when I try to modify the chat even specifically with commandhelper its just null now

**Comment by drtshock** [comment]
What? What exactly are you doing?

**Comment by PhanaticD** [comment]
modifying the chat format, its happening with my skywars plugin as well which modifies the chat format

**Comment by drtshock** [comment]
Can you show me the code and then what you have in essentials as the chat setup? Then also the stack trace if there is one.

**Comment by drtshock** [comment]
Still waiting on ^
