### ISSUE TITLE
Chat prefixes are not visible when using EssentialsX, zPermissions, and Vault

### ISSUE THREAD

**Issue by jflory7** [drtshock/Essentials#35]
As determined in [this thread](http://www.spigotmc.org/threads/chat-prefixes-disappeared-essentialsxchat-zpermissions-vault.67284/) on Spigot, there seems to be an incompatibility when using these three plugins in conjunction with one another.

I am using [PaperSpigot 1.8.4](https://hub.spigotmc.org/stash/projects/PAPER/repos/paperspigot/browse) as my server software (_git-PaperSpigot-5136053-db5fd9c_ (MC: 1.8.4), which is the latest as of the time of filing). I am using Build 83 of the EssentialsX suite (EssentialsX, EssentialsXChat, EssentialsXSpawn), [Vault 1.5.3](http://dev.bukkit.org/bukkit-plugins/vault/), and zPermissions, and Build 7 of [Spigot-zPermissions](https://hub.spigotmc.org/jenkins/job/zPermissions/).

Upon testing with the original Spigot-Essentials build of EssentialsChat, my chat prefixes worked fine. However, when switching to EssentialsXChat, my prefixes no longer appeared. I tested this on two separate servers, both with zPermissions Build 7 and Build 83 of EssentialsX; however, one server did have Vault and the other did not. The server without Vault did not lose the prefixes but the one running Vault did lose prefixes. Through this, I was able to determine it shouldn't be an issue with the software that I'm running.

Upon looking through zPermission's `config.yml`, I saw a few settings regarding Vault and I wondered if these might have to be configured in a certain way to ensure that EssentialsXChat and Vault got along nicely.
![Screenshot of zPermissions config's Vault settings](http://i.imgur.com/GkpBEjY.png)

However, the weirdest part is that the Spigot-Essentials EssentialsChat worked fine but EssentialsXChat had issues displaying the prefix.

If any other information is needed, please just ask and I can provide.

**Comment by TWSSYesterday** [comment]
Also having this issue on 1.8.3 Spigot.

**Comment by vemacs** [comment]
Can reproduce on 1.8.3 PaperSpigot as well.

**Comment by drtshock** [comment]
@jflory7 can you try the latest build and see if it fixes it? Build #87

**Comment by jflory7** [comment]
@drtshock Confirmed, fixed! Thanks!

**Comment by vemacs** [comment]
@jflory7 We removed the individual permissions plugin implementations due to them generally being pointless and not UUID updated. Install Vault, I've updated the readme to reflect this.

**Comment by jflory7** [comment]
@vemacs Alright, I see. I added Vault and everything is working well now. Cheers!

**Comment by jflory7** [comment]
@drtshock @vemacs I'm not sure if this was known or not, but running my server without Vault last night allowed several players to gain access to some administrative commands, like /getpos, /nick, and several others (although not ones like /gamemode, /tp, /give, etc.). Installing Vault instantly fixed this for me. I read through all of the changelogs on the CI server before updating my EssentialsX from 83 to 106, and I didn't see any note of Vault being *required* as a dependency anywhere. You may want to broadcast this change somewhere on the Jenkins CI server as well – anyone who is using newer builds without Vault could be risking player-initiated damage to their server.

**Comment by vemacs** [comment]
@jflory7 That shouldn't happen as permissions checks would still be performed with the Vault-less implementation. Do you have any logs?
