### ISSUE TITLE
Timer bypass not working

### ISSUE THREAD

**Issue by TWSSYesterday** [drtshock/Essentials#38]
Users with essentials.teleport.timer.bypass aren't bypassing the timer set.
Using latest version and 1.8.3 Spigot: http://i.imgur.com/An0mOBG.png (Spigot version)
Using PermissionsEx 1.23.2 and latest Vault

**Comment by drtshock** [comment]
Try on build 90 or newer.

**Comment by vemacs** [comment]
Can't reproduce with latest builds.

**Comment by TWSSYesterday** [comment]
No longer occurs, thanks
