### ISSUE TITLE
EssentialsX not accepting * permission

### ISSUE THREAD

**Issue by Kakifrucht** [drtshock/Essentials#45]
Weirdly essentials.* and every other permission wildcard currently does not work and shows the no permission error.
I have Moderators with basically just *, they can't use any Essentials commands for instance.
I checked the plugin.yml, however it is not modified, so the issue lies somewhere in the source.
It works with spigots essentials. It's probably this commit https://github.com/drtshock/Essentials/commit/ac0858dcdbf4dd12e1c1b27d4de822646e625a1b

I'm using the latest 1.8.3 build, the latest GroupManager and the latest EssentialsX build.

**Comment by vemacs** [comment]
That commit probably has nothing to do with it. The permissions handler only is done for cosmetic stuff.

**Comment by Kakifrucht** [comment]
Nice, thank you. 
You should get permission to merge imo :D
