### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zRiaz** [drtshock/Essentials#48]
Since the newest update of EssentialsX Ive been getting this on join.
http://pastebin.com/ZaJyiR72

(Very latest build)

Running 1.8.6 PaperSpigot (Very Latest build there too)

**Comment by Kakifrucht** [comment]
Are you running Vault (which version)?

**Comment by zRiaz** [comment]
Yea, dont know version and cant check atm either.. But I think its one of the newest as I installed it about a week ago

**Comment by drtshock** [comment]
Can you paste your startup log in a gist or pastebin please.

**Comment by vemacs** [comment]
What permissions plugin are you using?

**Comment by zRiaz** [comment]
GroupManager

**Comment by zRiaz** [comment]
Does it not support GroupManager anymore??

**Comment by vemacs** [comment]
?

**Comment by Kakifrucht** [comment]
I just tested the fix, does not work.

**Comment by vemacs** [comment]
Next build please

**Comment by Kakifrucht** [comment]
Yes, everything is fully functional. Thanks!

**Comment by vemacs** [comment]
@Kakifrucht @zRiaz Do you mind testing this with the latest build as well, did some code cleanup

**Comment by Kakifrucht** [comment]
104 is working too.

**Comment by vemacs** [comment]
104 has an issue with spam on shutdown, 105 should fix that

**Comment by Kakifrucht** [comment]
105 prints following to console and doesnt use GroupManager: Essentials: Using config file enhanced permissions.

**Comment by vemacs** [comment]
Try 106.

**Comment by Kakifrucht** [comment]
Working.
