### ISSUE TITLE
Fix essentials lore behaviour

### ISSUE THREAD

**Issue by Kakifrucht** [drtshock/Essentials#49]
When getting a custom mobspawner with /i 52:50 1 or /give player 52:50 1 (should be creeper spawner), you get a custom spawner, however when using /i 52:50 1 lore:Test it still works, /give player 52:50 1 lore:Test does not work and gives you a default mobspawner.

This has been discussed here https://github.com/drtshock/Essentials/issues/22

**Comment by vemacs** [comment]
This looks fixed with 106.

**Comment by Kakifrucht** [comment]
And working, too, thanks.
Any idea about the permissions?

**Comment by vemacs** [comment]
File as another bug please
