### ISSUE TITLE
Need to review mob effects in ess protect

### ISSUE THREAD

**Issue by drtshock** [drtshock/Essentials#5]

**Comment by SupaHam** [comment]
Can you elaborate?

**Comment by drtshock** [comment]
no :(

**Comment by SupaHam** [comment]
Should I just close? :P

**Comment by Kakifrucht** [comment]
Wasn't this ticket imported when you forked the project?
If so, @khobbits could most likely elaborate.

Side question, how come this is not a fork anymore?

**Comment by drtshock** [comment]
So we can do things that forks can't do. Vemacs requested it initially and I agreed with his reasoning (don't remember exactly what).

**Comment by khobbits** [comment]
I doubt it, Essentials had issue tracking disabled.

No idea on the fork thing, maybe they were scared i'd delete the ess project and thus their fork.

**Comment by Kakifrucht** [comment]
At times I feel like @khobbits really really hates this project :sweat_smile: 

Thanks for the clarifications.

Also it [seems like](https://help.github.com/articles/deleting-a-repository/) deleting a public project does not remove the forks, this only applies to private repos.

**Comment by khobbits** [comment]
essx? i love it, it means i don't have to develop ess anymore.

Edit: I spent something like 5 years maintaining Ess, it's nice to be able to say 'i don't need to do this anymore because someone else is doing it'.  I can basically walk away hands clean :p

**Comment by SupaHam** [comment]
**_We'll make it bigger, better, stronger._**

Make Essentials Great Again!

**Comment by drtshock** [comment]
> No idea on the fork thing, maybe they were scared i'd delete the ess project and thus their fork.

Nothing to do with that. I think it was something about being able to see more analytics in the repo and other things that you can't do with forks.

**Comment by SupaHam** [comment]
Should this be closed then @drtshock?

**Comment by drtshock** [comment]
Why not
