### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by adendrag** [drtshock/Essentials#52]
Hi. Getting this error. Using with the latest Spigot version. http://pastebin.com/nTr1qqnc

**Comment by drtshock** [comment]
Can you paste what happens in the log before that as well that leads to that error?

**Comment by adendrag** [comment]
Entire startup log is this. http://pastebin.com/jMAU464A

**Comment by adendrag** [comment]
The error I provided was during startup.

**Comment by vemacs** [comment]
03.06 08:43:51 [Server] ERROR java.lang.NoSuchMethodError: java.nio.CharBuffer.subSequence(II)Ljava/nio/CharBuffer;

This doesn't seem to be our issue.

**Comment by adendrag** [comment]
Have any idea as how to fix?

**Comment by vemacs** [comment]
Going to ask @drtshock to look into the CI server. Update to Java 7 in the meantime.

**Comment by adendrag** [comment]
Thanks
