### ISSUE TITLE
GroupManagerX?

### ISSUE THREAD

**Issue by zRiaz** [drtshock/Essentials#54]
Will you update GroupManager too? :]

I seem to have found a few issues in it, currently on 1.8.7 using the /manuaddv command I tried: /manuaddv Riaz prefix '[test prefix] ' which ended up not giving me any prefix at all..

I'm just starting to use the variable system in GroupManager as a solution for Staff Prefixes. And yea.. It didn't seem to work. I tried multiple times with no luck at all. 

So seems like the variables feature is broken in GM. Also Im not sure if this is a thing already, but if you could do something with EssChat & GroupManager which would basically make a option to add {prefix} which would be the prefix given by /manuaddv (name) prefix (prefix). 

As mentioned, Im not sure if thats already implemented or not. If its not, then I would love to see it implemented soon.. 

So yea. If you don't want to make a GroupManagerX I guess ill have to learn PEX :[

**Comment by vemacs** [comment]
Read the startup log. Install Vault.

**Comment by Kakifrucht** [comment]
@vemacs @drtshock I personally didn't come accross any issues with GroupManager right now, but if it breaks, would you guys be willing to support it? ;)

**Comment by zRiaz** [comment]
Uhm i have vault..

**Comment by vemacs** [comment]
Can't reproduce. GroupManagerX + EssentialsX works fine with Vault 1.5.3 for me and basically everyone else.

**Comment by drtshock** [comment]
Don't really want to support groupmanager.

**Comment by zRiaz** [comment]
Im dumb af, I forgot about the add-prefix-suffix.. Anyways, is there even a GroupManagerX? (I couldn't see it on the Jekins)

**Comment by vemacs** [comment]
No.

**Comment by GenericOnlineGaming** [comment]
if there is no group manager how what do i use to add groups and ranks?

**Comment by drtshock** [comment]
Use a different plugin.
