### ISSUE TITLE
New variable in the language file.

### ISSUE THREAD

**Issue by ISanderI** [drtshock/Essentials#56]
So, basically some players around have different amount of homes and sometimes they are unsure of exactly how many they have.

So I thought if you could add some more variables to the language file for this:
homes=\u00a76Homes\:\u00a7r {0}

To make it something like this: homes=\u00a77Homes\{sethomes}/{maxhomes}:\u00a7r {0}
Or any other variable suitable.. But thats the basic idea. So it would display:
Homes(3/8): (name), (name), (name)

(This would also somehow hook into HomeLimit :p)

Its nothing major and I don't see how it would be a issue to add, personally I think it would come in really handy for a lot of people.

**Comment by vemacs** [comment]
The home limit is already passed as a parameter to the translation function:
https://github.com/drtshock/Essentials/blob/e33c42e123760c3d93547eeb152a2505165adc30/Essentials/src/com/earth2me/essentials/commands/Commandhome.java#L68

**Comment by vemacs** [comment]
It's already there. I'll change the default as that makes sense.

**Comment by vemacs** [comment]
Use `homes=\u00a76Homes ({1}/{2}):\u00a7r {0}`, that should work.
