### ISSUE TITLE
/Baltop not working

### ISSUE THREAD

**Issue by rubota** [drtshock/Essentials#57]
Yes, I'm the guy from earlier. I finally figured out what's causing it, sorta. I narrowed the error coding to 

12.06 14:41:09 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
12.06 14:41:09 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
12.06 14:41:09 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
12.06 14:41:09 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
12.06 14:41:09 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Entity$Spigot

/baltop works up to the point this shows in the console. This has happened several times so I can defiantly confirm it. When this happens, nothing shows up in the console at the point you say the command /baltop, but this coding pops up overtime the command /baltop stops working. 

As you can guess the command works up to the point this command shows and then doesn't show anything. Including any errors in the console or any invalid command error shown on screen. Nothing shows at the time of command, besides this error code before it stops. 

I'm running Bukkit 1.8.5. 

here's the rest of the log:

12.06 14:47:21 [Server] INFO Admins: [AFK][CEO]Ergenta
12.06 14:46:17 [Server] INFO Admins: [AFK][CEO]Ergenta
12.06 14:45:13 [Server] INFO Admins: [CEO]Ergenta
12.06 14:44:08 [Server] INFO Admins: [CEO]Ergenta
12.06 14:43:04 [Server] INFO Admins: [CEO]Ergenta
12.06 14:41:59 [Server] INFO Admins: [CEO]Ergenta
12.06 14:41:59 [Multicraft] Skipped 2 lines due to rate limit (30/s)
12.06 14:41:09 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
12.06 14:41:09 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
12.06 14:41:09 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
12.06 14:41:09 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
12.06 14:41:09 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Entity$Spigot
12.06 14:41:09 [Server] INFO ... 10 more
12.06 14:41:09 [Server] INFO at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
12.06 14:41:09 [Server] INFO at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
12.06 14:41:09 [Server] INFO at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
12.06 14:41:09 [Server] INFO at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
12.06 14:41:09 [Server] INFO at com.earth2me.essentials.UserMap.load(UserMap.java:18)
12.06 14:41:09 [Server] INFO at com.earth2me.essentials.UserMap.load(UserMap.java:134)
12.06 14:41:09 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/bukkit/entity/Entity$Spigot
12.06 14:41:09 [Server] INFO ... 3 more
12.06 14:41:09 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
12.06 14:41:09 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
12.06 14:41:09 [Server] INFO at com.earth2me.essentials.commands.Commandbalancetop$Calculator.run(Commandbalancetop.java:98)
12.06 14:41:09 [Server] INFO at com.earth2me.essentials.UserMap.getUser(UserMap.java:90)
12.06 14:41:09 [Server] INFO at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
12.06 14:41:09 [Server] INFO at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
12.06 14:41:09 [Server] INFO at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
12.06 14:41:09 [Server] INFO at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
12.06 14:41:09 [Server] INFO Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/bukkit/entity/Entity$Spigot
12.06 14:41:09 [Server] INFO at java.lang.Thread.run(Thread.java:745)
12.06 14:41:09 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
12.06 14:41:09 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
12.06 14:41:09 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
12.06 14:41:09 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Essentials v2.0.1-b127 generated an exception while executing task 122
12.06 14:41:09 [Server] WARN Exception in thread "pool-3-thread-27" 
12.06 14:41:09 [Multicraft] Skipped 2 lines due to rate limit (30/s)
12.06 14:41:07 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
12.06 14:41:07 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
12.06 14:41:07 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
12.06 14:41:07 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
12.06 14:41:07 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Entity$Spigot
12.06 14:41:07 [Server] INFO ... 10 more
12.06 14:41:07 [Server] INFO at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
12.06 14:41:07 [Server] INFO at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
12.06 14:41:07 [Server] INFO at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
12.06 14:41:07 [Server] INFO at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
12.06 14:41:07 [Server] INFO at com.earth2me.essentials.UserMap.load(UserMap.java:18)
12.06 14:41:07 [Server] INFO at com.earth2me.essentials.UserMap.load(UserMap.java:134)
12.06 14:41:07 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/bukkit/entity/Entity$Spigot
12.06 14:41:07 [Server] INFO ... 3 more
12.06 14:41:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
12.06 14:41:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
12.06 14:41:07 [Server] INFO at com.earth2me.essentials.commands.Commandbalancetop$Calculator.run(Commandbalancetop.java:98)
12.06 14:41:07 [Server] INFO at com.earth2me.essentials.UserMap.getUser(UserMap.java:90)
12.06 14:41:07 [Server] INFO at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
12.06 14:41:07 [Server] INFO at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
12.06 14:41:07 [Server] INFO at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
12.06 14:41:07 [Server] INFO at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
12.06 14:41:07 [Server] INFO Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/bukkit/entity/Entity$Spigot
12.06 14:41:07 [Server] INFO at java.lang.Thread.run(Thread.java:745)
12.06 14:41:07 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
12.06 14:41:07 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
12.06 14:41:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
12.06 14:41:07 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Essentials v2.0.1-b127 generated an exception while executing task 120
12.06 14:41:07 [Server] WARN Exception in thread "pool-3-thread-25" 
12.06 14:41:07 [Multicraft] Skipped 2 lines due to rate limit (30/s)
12.06 14:41:04 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
12.06 14:41:04 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
12.06 14:41:04 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
12.06 14:41:04 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
12.06 14:41:04 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Entity$Spigot
12.06 14:41:04 [Server] INFO ... 10 more
12.06 14:41:04 [Server] INFO at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
12.06 14:41:04 [Server] INFO at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
12.06 14:41:04 [Server] INFO at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
12.06 14:41:04 [Server] INFO at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
12.06 14:41:04 [Server] INFO at com.earth2me.essentials.UserMap.load(UserMap.java:18)
12.06 14:41:04 [Server] INFO at com.earth2me.essentials.UserMap.load(UserMap.java:134)
12.06 14:41:04 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/bukkit/entity/Entity$Spigot
12.06 14:41:04 [Server] INFO ... 3 more
12.06 14:41:04 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
12.06 14:41:04 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
12.06 14:41:04 [Server] INFO at com.earth2me.essentials.commands.Commandbalancetop$Calculator.run(Commandbalancetop.java:98)
12.06 14:41:04 [Server] INFO at com.earth2me.essentials.UserMap.getUser(UserMap.java:90)
12.06 14:41:04 [Server] INFO at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
12.06 14:41:04 [Server] INFO at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
12.06 14:41:04 [Server] INFO at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
12.06 14:41:04 [Server] INFO at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
12.06 14:41:04 [Server] INFO Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/bukkit/entity/Entity$Spigot
12.06 14:41:04 [Server] INFO at java.lang.Thread.run(Thread.java:745)
12.06 14:41:04 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
12.06 14:41:04 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
12.06 14:41:04 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
12.06 14:41:04 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Essentials v2.0.1-b127 generated an exception while executing task 118
12.06 14:41:04 [Server] WARN Exception in thread "pool-3-thread-20" 
12.06 14:40:55 [Server] INFO Admins: [CEO]Ergenta
12.06 14:40:19 [Server] INFO [world]**rbn [CEO]Ergenta ew
12.06 14:39:50 [Server] INFO Admins: [CEO]Ergenta
12.06 14:39:50 [Multicraft] Skipped 78 lines due to rate limit (30/s)
12.06 14:39:39 [Server] INFO at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199) ~[craftbukkit-1.8.5-20150523a.jar:git-Bukkit-7bc9c08]
12.06 14:39:39 [Server] INFO Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/bukkit/entity/Entity$Spigot
12.06 14:39:39 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
12.06 14:39:39 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:540) [craftbukkit-1.8.5-20150523a.jar:git-Bukkit-7bc9c08]
12.06 14:39:39 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:632) [craftbukkit-1.8.5-20150523a.jar:git-Bukkit-7bc9c08]
12.06 14:39:39 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:336) [craftbukkit-1.8.5-20150523a.jar:git-Bukkit-7bc9c08]
12.06 14:39:39 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:676) [craftbukkit-1.8.5-20150523a.jar:git-Bukkit-7bc9c08]
12.06 14:39:39 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [craftbukkit-1.8.5-20150523a.jar:git-Bukkit-7bc9c08]
12.06 14:39:39 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_65]
12.06 14:39:39 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_65]
12.06 14:39:39 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.8.5-20150523a.jar:git-Bukkit-7bc9c08]
12.06 14:39:39 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.8.5-20150523a.jar:git-Bukkit-7bc9c08]
12.06 14:39:39 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.8.5-20150523a.jar:git-Bukkit-7bc9c08]
12.06 14:39:39 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:939) [craftbukkit-1.8.5-20150523a.jar:git-Bukkit-7bc9c08]
12.06 14:39:39 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1079) [craftbukkit-1.8.5-20150523a.jar:git-Bukkit-7bc9c08]
12.06 14:39:39 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:625) [craftbukkit-1.8.5-20150523a.jar:git-Bukkit-7bc9c08]
12.06 14:39:39 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) [craftbukkit-1.8.5-20150523a.jar:git-Bukkit-7bc9c08]
12.06 14:39:39 [Server] INFO at com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:67) [MassiveCore.jar:?]
12.06 14:39:39 [Server] INFO at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:349) [MassiveCore.jar:?]
12.06 14:39:39 [Server] INFO at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:306) [MassiveCore.jar:?]

**Comment by vemacs** [comment]
12.06 14:39:50 [Multicraft] Skipped 78 lines due to rate limit (30/s)

Pastebin the actual server log please.

**Comment by rubota** [comment]
Ah, you again. If you bother to stop typing and actually payed attention to what happened, you would of realized I was on bukkit before I went to spigot. Someone on your side advised me to switch because the plugin wasn't working. 

You were just another case of "Lets on in and think we know everything about whats going on."

**Comment by vemacs** [comment]
You know, not being a total dick would get you more help. Remove Factions/MassiveCore and report back.

**Comment by rubota** [comment]
you know, not being a complete douche bag will get you further in life.

**Comment by rubota** [comment]
Keep your plugin broken then. You do you.

**Comment by lol768** [comment]
Insulting contributors who've taken their time to give you advice isn't a good way to get support :(

**Comment by rubota** [comment]
I did all that earlier, you know when you were mocking me for having spigot. I only had essentials, group manager and vault installed and it did the same thing. Ask one of your team mates.

**Comment by rubota** [comment]
being a complete douche isn't a good way to find errors in something you made.

**Comment by drtshock** [comment]
You came in and were berating helpers in my channel from the start. Go use someone else's plugin if you have so many issues with ours.

**Comment by vemacs** [comment]
Last word:

![](http://i.imgur.com/vi08DgX.png)

Can't reproduce, user didn't provide full logs, user has serious entitlement issues.
