### ISSUE TITLE
Commands Not Working

### ISSUE THREAD

**Issue by pepsiisgross** [drtshock/Essentials#58]
Hey,

I'm sorry if this is the wrong place to post this. This is like my second ever time using github. So, I tired installing EssentialsX, but the commands wouldn't work.

I'm not sure what Spigot version we're running, but I could probably find out if need be. Do I need a specific version?

It may help to know that the server was running while making the changes, but ALL new data was uploaded and the old was deleted.

**Comment by vemacs** [comment]
Please pastebin your full startup log (`logs/latest.log`)

**Comment by pepsiisgross** [comment]
This is the error: http://hastebin.com/obuwamejox.avrasm

Pretty sure it's from the wrong Spigot version.

**Comment by drtshock** [comment]
Update to build 130.
