### ISSUE TITLE
Don't send another /tpa request to recipient if one is already pending from requester

### ISSUE THREAD

**Issue by RoboMWM** [drtshock/Essentials#59]
Currently, it is possible to spam the /tpa command to the same recipient multiple times (they receive a new request regardless if they have already been requested.) Instead, it should work like this:
1. Steve sends /tpa alex
2. Alex receives request for /tpaccept or /tpdeny
3. Steve sends /tpa alex again before Alex has responded to the request (and within the request timeout)
4. Alex should _not_ receive another request

Optionally, /tpdeny could halt repeated /tpa requests (either use the request timeout or a new config option)

**Comment by drtshock** [comment]
Can you not also /ignore <player> or /tptoggle? Though I do like the idea you outlined with not getting an additional request when another is pending.

**Comment by Kakifrucht** [comment]
Yes this is annoying, no doubt.
I handled this on my server by adding command cost to tpa (Essentials supports this), and staff used toggled it off, however there really is no reason to again show that a request have been made, when it didn't time out yet or when it has been denied.

**Comment by RoboMWM** [comment]
Well, it'd be nice to not have to /tptoggle for all players when it's just one player.

Or you could add /tptoggle (player name)

**Comment by drtshock** [comment]
@RoboMWM you can just /ignore

**Comment by RoboMWM** [comment]
I'm assuming that also ignore chat messages as well?

**Comment by KyrneDev** [comment]
It does ignore chat, there should be a cool down because it is very annoying to get a million requests from players it completely fills the chat can nothing else can be seen. Yes tptoggle would work but what if you still want to get requests?

**Comment by SupaHam** [comment]
This has been fixed in 3245ce1. You can grab the fix from [build 407](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
