### ISSUE TITLE
Silent ban messages?

### ISSUE THREAD

**Issue by TWSSYesterday** [drtshock/Essentials#60]
Currently if you have access to view ban messages you can see the IP of the user that's banned.

**Comment by drtshock** [comment]
So a separate permission for ip ban broadcasting?

**Comment by TWSSYesterday** [comment]
Yup, also is there an easy way of grabbing all of these permissions? Obviously things will change as the plugin progresses.

**Comment by drtshock** [comment]
The plugin.yml will have everything.

**Comment by TWSSYesterday** [comment]
I know, but I meant something like http://wiki.ess3.net/wiki/Command_Reference/Perm

**Comment by FlippantCactus** [comment]
ty <3
