### ISSUE TITLE
World defining broken?

### ISSUE THREAD

**Issue by mibby** [drtshock/Essentials#61]
Since updating from Spigot-Essentials dev 12 to EssentialsX dev 156, logblock seems to be mixing up the nether and the overworld. Creating logs in the nether by breaking/placing blocks then going to the same coordinates in the overworld, those logs are present. This does not occur with Spigot-Essentials.

Is something wrong with world defining - not being separate?

**Comment by drtshock** [comment]
I just don't see how this could be an essentials issue. We haven't touched anything with worlds.

**Comment by vemacs** [comment]
I use EssX with LogBlock with no issues regarding world definition.

**Comment by mibby** [comment]
Quite odd. I'm not sure why I am experiencing duplicate logs at the same coordinates on each world then since updating to EssX. I'll run some more tests tonight.

**Comment by mibby** [comment]
My apologies. It seems LogBlock broke when updating to the latest Spigot with EssX.
