### ISSUE TITLE
A way to shift-sell stacks via EssEco signs

### ISSUE THREAD

**Issue by cooperisdunn** [drtshock/Essentials#65]
Player A has 10000 cactus he needs to sell.
The shop sign that will give him money for his cactus only takes one at a time.
My request is a way to shift-click the sign, scaling the price, and allowed Player A to happily sell all of his cactus for the correct amount of money.

Please label this enhancement. Thank you!

**Comment by vemacs** [comment]
I need this on my own server as well, will probably implement it soon

**Comment by cooperisdunn** [comment]
Awesome :-)

**Comment by drtshock** [comment]
+1 @vemacs

**Comment by TheJadyha** [comment]
Agreed

**Comment by SupaHam** [comment]
I'll make shift-clicking sell the whole stack the player is holding.

**Comment by SupaHam** [comment]
This has been introduced in 87adbb4. You can grab the feature from [build 408](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

**Comment by netherstar** [comment]
are the option to disable this feature in config? if no, please add it, i dont want this feature on my server :(

**Comment by SupaHam** [comment]
@tuanjr Please make a separate issue for this request.
