### ISSUE TITLE
Cannot spawn monster spawners

### ISSUE THREAD

**Issue by silverbrit** [drtshock/Essentials#67]
Trying to spawn in some monster spawners either using '/give {username} 52 {amount}' or '/i 52 {amount} yields the error "Error: Can't spawn entity ID 0 from mob spawners."

Not sure if this is truly a bug within essentials or I'm messing up somewhere with my syntax. Those commands both used too work and I rely on them to give my donators spawners whenever they donate.

Essentials version: 2.0.1-b156
Spigot version: git-Spigot-f928e7a-e91aed8 (MC: 1.8.7)

**Comment by Kakifrucht** [comment]
Confirming this issue, it should default to a standard mobspawner.

To fix this situation, simply use /i 52:50 1

**Comment by silverbrit** [comment]
Thanks for the temporary solution.
